all:
  children:
    sap:
      children:
        hana:
          hosts:
            sapddhdb1.demo.josh.lab.msp.redhat.com:
            sapddhdb2.demo.josh.lab.msp.redhat.com:
            sapdqhdb1.demo.josh.lab.msp.redhat.com:
            sapdqhdb2.demo.josh.lab.msp.redhat.com:
            sapdphdb1.demo.josh.lab.msp.redhat.com:
            sapdphdb2.demo.josh.lab.msp.redhat.com:
        app_servers:
          hosts:
            sapddapp1.demo.josh.lab.msp.redhat.com:
            sapddapp2.demo.josh.lab.msp.redhat.com:
            sapddapp3.demo.josh.lab.msp.redhat.com:
            sapddapp4.demo.josh.lab.msp.redhat.com:
            sapdqapp1.demo.josh.lab.msp.redhat.com:
            sapdpapp1.demo.josh.lab.msp.redhat.com:
        clusters:
          hosts:
            sapddcl1.demo.josh.lab.msp.redhat.com:
            sapddcl2.demo.josh.lab.msp.redhat.com:
        dev:
          hosts:
            sapddhdb1.demo.josh.lab.msp.redhat.com:
            sapddhdb2.demo.josh.lab.msp.redhat.com:
            sapddapp1.demo.josh.lab.msp.redhat.com:
            sapddapp2.demo.josh.lab.msp.redhat.com:
            sapddapp3.demo.josh.lab.msp.redhat.com:
            sapddapp4.demo.josh.lab.msp.redhat.com:
            sapddcl1.demo.josh.lab.msp.redhat.com:
            sapddcl2.demo.josh.lab.msp.redhat.com:
        qa:
          hosts:
            sapdqhdb1.demo.josh.lab.msp.redhat.com:
            sapdqhdb2.demo.josh.lab.msp.redhat.com:
            sapdqapp1.demo.josh.lab.msp.redhat.com:
        prod:
          hosts:
            sapdphdb1.demo.josh.lab.msp.redhat.com:
            sapdphdb2.demo.josh.lab.msp.redhat.com:
            sapdpapp1.demo.josh.lab.msp.redhat.com:
        group_1:
         hosts:
            sapddapp1.demo.josh.lab.msp.redhat.com:
        group_2:
         hosts:
            sapddapp2.demo.josh.lab.msp.redhat.com:
        group_3:
         hosts:
            sapddapp3.demo.josh.lab.msp.redhat.com:
        group_4:
         hosts:
            sapddapp4.demo.josh.lab.msp.redhat.com:
