---

additional_storage:
  - size_gb: 500
    scsi_controller: 0
    unit_number: 1
    datastore: storage04-nfs-lun0
provisioning:
  satellite:
    username: admin
    password: 'R3dh4t123!'
    url: "https://satellite.demo.josh.lab.msp.redhat.com"
    validate_certs: no
  hostgroup: kickstart-rhel8.2-vlan146
  cpus: 8
#  memory_mb: 65536
  memory_mb: 98304
  method: bootdisk
  organization: josh-demo
  location: josh-demo
storage_pools:
  - name: sap
    disks:
      - sdb
    volumes:
      - name: data
        size: "128 GiB"
        mount_point: "/hana/data"
        state: present
      - name: log
        size: "64 GiB"
        mount_point: "/hana/log"
        state: present
      - name: shared
        size: "256 GiB"
        mount_point: "/hana/shared"
        state: present
      - name: sap
        size: "50 GiB"
        mount_point: "/usr/sap"
        state: present

# HANA settings
sap_hana_deployment_bundle_path: /software/HANA_installation
sap_hana_deployment_bundle_sar_file_name: IMDB_SERVER20_046_0-80002031.SAR
sap_hana_deployment_sapcar_path: /software/SAPCAR
sap_hana_deployment_sapcar_file_name: SAPCAR_1311-80000935.EXE
sap_hana_deployment_root_password: "R3dh4t123!"
sap_hana_deployment_sapadm_password: "R3dh4t123!"
sap_hana_deployment_hana_instance_number: "00"
sap_hana_deployment_hana_env_type: development
sap_hana_deployment_hana_mem_restrict: "n"
sap_hana_deployment_common_master_password: "R3dh4t123!"
sap_hana_deployment_sidadm_password: "R3dh4t123!"
sap_hana_deployment_hana_db_system_password: "R3dh4t123!"
sap_hana_deployment_ase_user_password: "R3dh4t123!"
sap_hana_deployment_apply_license: false
sap_hana_hsr_hana_instance_number: "00"
sap_hana_hsr_hana_db_system_password: "R3dh4t123!"
